packages/gatsby-theme-newrelic/gatsby-ssr.js, packages/gatsby-theme-newrelic/gatsby/on-pre-render-html.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles.js
Closes #14 
Ensure the font families load correctly and the CSS variables are defined with the `:root` selector.
=> Typography styles

.github/workflows/pr_merged.yml
Fixes failing action by removing the dependency on the only job in the `pr_merged` workflow.
=> Fix failing action

.github/workflows/release.yml, demo/CHANGELOG.md, demo/package.json, lerna.json, package.json, packages/gatsby-theme-newrelic/CHANGELOG.md, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/package.json
Sets up a GitHub action to generate and publish a release on merge to `main` using lerna.
* Closes #2 
* Closes #7
=> Generate & Publish Releases via GitHub Actions

.github/workflows/release.yml, lerna.json, package.json
The versioning is not quite setup right. This updates the configuration to try and properly generates changelogs and github releases when we create new versions.
=> Release tweaking

packages/gatsby-theme-newrelic/README.md
[Rendered](https://github.com/newrelic/gatsby-theme-newrelic/tree/jerelmiller-patch-1/packages/gatsby-theme-newrelic)
=> Fix YouTube and Wistia video examples

packages/gatsby-theme-newrelic/src/components/Surface.js
Ensures the `Surface` component uses the dark mode box shadow.
=> Add dark mode box shadow

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/Tag.js, packages/gatsby-theme-newrelic/src/components/TagList.js
Create a `<Tag />` and `<TagList />` component that can be used on the various sites. Implements the design used on the [open source site](https://opensource.newrelic.com)
=> Add a Tag component

packages/gatsby-theme-newrelic/src/components/ResultView.js
Closes https://github.com/newrelic/developer-website/issues/561
=> Use Tag component in ResultView, uppercase tag text

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/Overlay.js, packages/gatsby-theme-newrelic/src/hooks/useKeyPress.js, packages/gatsby-theme-newrelic/src/hooks/usePortal.js
* Better handling of escape key to close the overlay
* Add handler to trigger search with the keypress of `/` 🤓
* Make the header the width of the site layout
* add a scale effect when animating in/out of the search overlay
=> Search improvements

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/Button.js, packages/gatsby-theme-newrelic/src/components/DarkModeToggle.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/utils/constants.js
Closes #690
* Adds click track events in split.io for all header actions. 
* Unifies the tracking events by naming them all the same and providing a property to determine the action that was clicked
* Fixes the button size issue where outline buttons were slightly larger than the other buttons
=> Split.io tweaks + button size fix

CHANGELOG.md, demo/CHANGELOG.md, demo/package.json, lerna.json, packages/gatsby-theme-newrelic/package.json
=> Resolve merge conflict in `demo/package.json`

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/Callout.js
Added Callout component that can generate caution, important, and tip callouts. Added documentation to readme as well.
Closes #113
=> Callout component

packages/gatsby-theme-newrelic/src/components/Callout.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles.js
=> fix: make callout colors more subtle

packages/gatsby-theme-newrelic/gatsby/on-pre-render-html.js
Adds the Bizible tracking script to our websites.
* Relates to https://github.com/newrelic/developer-website/issues/803
=> Bizible tracking script

demo/gatsby-config.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/SearchInput.js, packages/gatsby-theme-newrelic/src/components/Spinner.js, packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js
Closes https://github.com/newrelic/docs-website/issues/175
Adds a search input in the header that allows a user to type a search query, then submit it to search.
=> Search input in the header

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/Table.js
Pulled in the table component from the docs site and added it to theme for global use across all the sites that use our theme.
=> Table component added to the theme

packages/gatsby-theme-newrelic/gatsby-browser.js, packages/gatsby-theme-newrelic/gatsby-ssr.js
When working to resolve the build issues with the theme, I forgot to add vital import statements to the files I updated. This PR fixes that issue.
=> Fixes to build issues

demo/src/pages/build-apps.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/ContributingGuidelines.js, packages/gatsby-theme-newrelic/src/components/GlobalFooter.js, packages/gatsby-theme-newrelic/src/components/SimpleFeedback.js, packages/gatsby-theme-newrelic/src/components/__tests__/SimpleFeedback.test.js, packages/gatsby-theme-newrelic/src/utils/createIssueURL.js
This PR simplifies the issue creation flow when interacting with the `<ContributingGuidelines />` component. Rather than sending the user to [a page to choose what issue type](https://github.com/newrelic/docs-website/issues/new/choose), they are placed on the new issue page with some fields filled out.
[Example Link](https://github.com/newrelic/gatsby-theme-newrelic/issues/new?labels=bug&title=Issue%3A+Build+Apps&body=%23%23+Description%0APage%3A+%5BBuild+Apps%5D%28https%3A%2F%2Fdeveloper.newrelic.com%2Fbuild-apps%29%0A%0A%5BNOTE%5D%3A+%23+%28Describe+the+problem+you%27re+encountering.%29%0A%5BTIP%5D%3A+%23+%28Do+NOT+give+us+access+or+passwords+to+your+New+Relic+account+or+API+keys%21%29%0A%0A%23%23+Steps+to+Reproduce%0A%0A%5BNOTE%5D%3A+%23+%28Please+be+as+specific+as+possible.%29%0A%0A%23 …
=> Simplified "Create Issue" Flow

packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
Source the locales as nodes instead of using a resolver to do so.
=> Source locales as nodes instead of via resolvers

packages/gatsby-theme-newrelic/README.md
[Rendered](https://github.com/newrelic/gatsby-theme-newrelic/blob/campfire/i18n-docs-redux/packages/gatsby-theme-newrelic/README.md)
=> Add documentation for updated i18n options

packages/gatsby-theme-newrelic/gatsby-node.js
not enough ☕   = lots of dumb mistakes
=> Adding missing helper function

packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/src/utils/related-resources/fetchRelatedResources.js
Makes a few more adjustments to update the swiftype code to work in the theme. Includes supplying a fallback for the `getPath` option.
=> Fixes for fetching related content

demo/gatsby-config.js, packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/src/components/SEO.js
* Adds the titleTemplate to SEO component and `gatsby-config.js`
* Removes double declaration of `getNodeByType`
=> SEO and gatsby node fixes

packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/src/components/SEO.js
Does some minor SEO component fixes
=> Minor SEO component fixes

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js
This PR updates the global footer copyright date.
=> chore: updated copyright date

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/Collapser.js
[Rendered](https://github.com/newrelic/gatsby-theme-newrelic/blob/jerel/document-new-stuff/packages/gatsby-theme-newrelic/README.md)
=> Document Collapser/CollapserGroup + other changes

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json
This PR removes the logic to handle the different buttons on each site, and makes all sign up buttons say Free Account.
=> chore: sign up button > free account

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/Table.js
Relates to https://github.com/newrelic/docs-website/issues/726
Add a min width to table cells and ensure tables scroll horizontally.
=> Scrollable tables

packages/gatsby-theme-newrelic/gatsby-browser.js, packages/gatsby-theme-newrelic/gatsby/on-client-entry.js, packages/gatsby-theme-newrelic/gatsby/on-route-update.js, packages/gatsby-theme-newrelic/src/components/DarkModeToggle.js, packages/gatsby-theme-newrelic/src/utils/getLocale.js
=> Add custom attributes for newrelic option 

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
Adds instrumentation to the `<GlobalHeader />`.
* Relates to https://github.com/newrelic/docs-website/issues/790
=> Add click handler for GlobalHeader

packages/gatsby-theme-newrelic/src/components/TableOfContents.js
Closes https://github.com/newrelic/docs-website/issues/794
Instruments clicks to the headings in the table of contents for the right rail
=> Instrument clicks on TableOfContents

packages/gatsby-theme-newrelic/src/i18n/translations/jp.json, packages/gatsby-theme-newrelic/src/utils/defaultOptions.js
=> Add Japanese translation strings

packages/gatsby-theme-newrelic/src/components/TableOfContents.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json, packages/gatsby-theme-newrelic/src/i18n/translations/jp.json
Partially addresses https://github.com/newrelic/docs-website/issues/966
Adds missing Japanese translation on `TableOfContents` component
=> Add missing Japanese translation on table of contents

packages/gatsby-theme-newrelic/src/components/Collapser.js
Closes https://github.com/newrelic/docs-website/issues/1065
If navigating to a collapser via a hash link, open the collapser.
=> Open the collapser if navigating to it via a hash link

packages/gatsby-theme-newrelic/src/components/ExternalLink.js, packages/gatsby-theme-newrelic/src/components/Link.js, packages/gatsby-theme-newrelic/src/utils/localization.js
Localizes external link paths to newrelic.com
=> Localizes paths for newrelic.com

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js, packages/gatsby-theme-newrelic/src/utils/localization.js
Handles the case of the localized link being the homepage
=> Handles localized home link

packages/gatsby-theme-newrelic/src/components/CreateIssueButton.js
Closes https://github.com/newrelic/docs-website/issues/1096
This PR adds the preferred labels to the create issue button component
=> chore: new labels

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js
Reverts newrelic/gatsby-theme-newrelic#324
=> Revert "chore: adds issuelabel prop to global footer"

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js
This PR correctly submits the changes from this original PR #324 with fix prefix in order to trigger a version bump on the theme.
=> fix: Add optional issueLabels prop to global footer

packages/gatsby-theme-newrelic/package.json, yarn.lock
We're having local issues with react-spring that this version appears to fix
=> Bump react-spring version

packages/gatsby-theme-newrelic/index.js
This was already created but hadn't been exported for use
=> chore: exporting the Dropdown component

packages/gatsby-theme-newrelic/src/components/Link.js
closes https://github.com/newrelic/docs-website/issues/3863
=> Optionally remove noreferrer from links to NR domain

.github/workflows/release-feature.yml, lerna.json
Does what it says on the tin.
I only think we can test this once it's merged in 🤷
=> Create a Release Workflow for the New Relic I/O Feature branch

packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/gatsby/on-pre-render-html.js, packages/gatsby-theme-newrelic/src/components/OneTrust.js
We no longer need to query GraphQL for this. This should _hopefully_ fix our issues with this branch not building.
=> Fix builds by removeing useStaticQuery

lerna.json
This is an attempt to get lerna to publish a new version to NPM.
🤞
=> Manually Adjusting Lerna Version

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
Re-adds IO to header nav menu.
Closes https://github.com/newrelic/gatsby-theme-newrelic/issues/484
Reverts this PR essentially: https://github.com/newrelic/gatsby-theme-newrelic/pull/470/files
=> Add IO to header nav

packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/src/components/Link.js, packages/gatsby-theme-newrelic/src/components/RelatedResources.js
Partially addresses https://github.com/newrelic/developer-website/issues/1692
=> Update related resources for quickstarts

packages/gatsby-theme-newrelic/src/i18n/translations/en.json, packages/gatsby-theme-newrelic/src/pages/404.js
Updates the english copy of the 404 page per UI Writing input.
I gave Julien relevant JSON to translate to japanese, but may take some time to get back, so will add that in subsequent PR.
Closes https://github.com/newrelic/gatsby-theme-newrelic/issues/511
=> [404] Update copy

packages/gatsby-theme-newrelic/src/components/Link.js
* swapped eventName & category arguments in link component since I think
they are reverse of what we want.
=> swap eventName & category arguments for tessen tracking in link

packages/gatsby-theme-newrelic/README.md
chore: add documentation for some of the components that weren't covered in the READ.ME
=> Theme Documentation - Components

packages/gatsby-theme-newrelic/src/components/SplitTextButton.js
Reverts newrelic/gatsby-theme-newrelic#584
=> Revert "add split event for default state"

demo/gatsby-node.js
Attempt to fix build error in github workflow check on releaes PR
=> chore(demo): add webpack config for demo site as well

demo/gatsby-config.js
our demo browser data has been reporting to the DevEx account, this updates to DocsEng
=> Update demo to report to DocsEng

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/SearchModal/SearchModal.js, packages/gatsby-theme-newrelic/src/components/SearchModal/useSearchQuery.js
=> Send filter information to tessen for search events

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/MobileHeader.js
=> Hide logo text at larger screen width

.github/workflows/pr-docs-eng-board-beta.yml
Add workflow file to add relevant PRs to this docs eng project board
https://github.com/orgs/newrelic/projects/65/views/5?layout=board
=> chore: add workflow file to add relevant PRs to project board

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/Video.js
=> Add mobile aspect ratio option for videos

packages/gatsby-theme-newrelic/src/components/SignupModal/SignupForm.js
removed unneeded CSS that i was experimenting with
=> fix: remove unneeded css

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/Skeleton.js
Added a skeleton component so we can use it with Split tests.
=> feat(components): skeleton

packages/gatsby-theme-newrelic/src/components/SignupModal/SignupForm.js
to QA - open the preview and click on the underlined links :)
=> chore: add legal disclaimer to signup modal form

packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/gatsby/on-client-entry.js, packages/gatsby-theme-newrelic/gatsby/on-pre-render-html.js, packages/gatsby-theme-newrelic/src/components/SEO.js
This is so that we can control when recaptcha gets rendered. I tested it out with linking to my PR in the docs site and it is all looking good!
=> Move recaptcha to SEO component 

packages/gatsby-theme-newrelic/src/components/SEO.js
https://issues.newrelic.com/browse/NR-21573
Tested on Safari and works.  Need to test on mobile as well.  
Also the ticket leaves open between the greyish background color and brand green.  This implements the background, but looking for opinions between this and the green.
=> NR-21573: Add theme color for top notch

demo/src/pages/index.js, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/CustomTextInput.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles/themes.js, packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/Icon.test.js.snap, packages/gatsby-theme-newrelic/src/icons/feather.js
https://user-images.githubusercontent.com/26727669/179238788-749f62c1-7401-49e5-aecd-530746de0a80.mov
https://issues.newrelic.com/browse/NR-32163
=> Custom Input Component - NR-32163

demo/src/pages/index.js, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/AnimatedCard.js, packages/gatsby-theme-newrelic/src/components/FlipCard.js
https://user-images.githubusercontent.com/39655074/180308997-8b4ff67f-5e31-4d88-bdd7-0ed841e0d6b5.mov
=> Add FlipCard component

packages/gatsby-theme-newrelic/package.json, yarn.lock
This is in an attempt to avoid any more DSG 500 errors.
=> fix: update gatsby version to 4.8.2

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/ContributingGuidelines.js, packages/gatsby-theme-newrelic/src/components/EditPageButton.js, packages/gatsby-theme-newrelic/src/components/Layout/PageTools.js, packages/gatsby-theme-newrelic/src/components/PageTools/PageTools.js, packages/gatsby-theme-newrelic/src/components/PageTools/Section.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json
Used git to checkout the SHA before the complex feedback form was created and reset the specific files for the original feedback form to be implemented.
=> fix: temporarily remove the complex feedback form

packages/gatsby-theme-newrelic/src/components/Walkthrough/WalkthroughStep.js
* `id` passes down to create anchor tags
* use h2 tags to create parity between other pages
=> Add `id` to WalkthroughStep and change h2 from h3

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/Tabs/Page.js
update styles to hide pages that aren't selected vs removing from DOM
=> fix: Tabs style update

demo/gatsby-config.js, packages/gatsby-theme-newrelic/gatsby-browser.js, packages/gatsby-theme-newrelic/gatsby/should-update-scroll.js
fix: add option to theme to allow listing certain routes that can all)ow scrolling via the gatsby api
=> shouldUpdateScroll Theme Option

packages/gatsby-theme-newrelic/gatsby/type-defs.js
Not 💯 on whether i needed to update the `.graphql` file or if that got generated by the file i updated.
=> update type defs for incoming theme options to use shouldUpdateScroll

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/InteractiveOutput.js
* Uses default value for interactive output 
* Replaces content once user starts typing
=> Use default value for interactive output

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/Side.js
This is to enable the side by side component div to take up the remaining height
=> Let side by side component accept full height

packages/gatsby-theme-newrelic/src/components/GlobalStyles/colors.js, packages/gatsby-theme-newrelic/src/components/MobileNavModal.js, packages/gatsby-theme-newrelic/src/components/NavLink.js
=> Update nav colors in the mobile modal

.github/workflows/pr-docs-eng-board-beta.yml, demo/gatsby-config.js
Update the environment variable name for the feedback recaptcha token
=> fix: update environment variable name for feedback recaptcha token

.github/workflows/pr-docs-eng-board-beta.yml, demo/gatsby-config.js
Reverts newrelic/gatsby-theme-newrelic#792
=> Revert "fix: update environment variable name for feedback recaptcha token"

packages/gatsby-theme-newrelic/src/i18n/translations/jp.json, packages/gatsby-theme-newrelic/src/i18n/translations/kr.json
=> 2 translated theme json files

demo/src/components/PropsDisplay.js, yarn.lock
=> feat: Add PropsDisplay component

demo/gatsby-config.js, packages/gatsby-theme-newrelic/gatsby/type-defs.js, packages/gatsby-theme-newrelic/src/utils/createTessen.js
adds a feedback attribute to gql schema
=> Theme Release - GQL schema update

demo/src/pages/index.js
WIP - This PR the skeleton to be filled in
=> feat: Homepage skeleton start

packages/gatsby-theme-newrelic/src/components/SimpleFeedback.js
update simple feedback form to use new feedback form verbiage and variables
=> fix: update simple feedback form

demo/src/content/steps.mdx, demo/src/data/sidenav.json, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/MDX.js, packages/gatsby-theme-newrelic/src/components/SideBySide.js, packages/gatsby-theme-newrelic/src/components/TutorialSteps/TutorialSection.js, packages/gatsby-theme-newrelic/src/components/TutorialSteps/TutorialStep.js, packages/gatsby-theme-newrelic/src/components/TutorialSteps/index.js, packages/gatsby-theme-newrelic/src/utils/mdx.js
you can check them out in an mdx page in the demo at `/steps`
=> Add step components

packages/gatsby-theme-newrelic/src/components/Tabs/Bar.js
trying to render `children` didn't work for mobile tabs from MDX pages because the text we need to render is nested two components deep. this change traverses the children of the component passed in until we get to an element that has no children and renders that, which for tabs is just a string
=> fix: get deepest descendent for mobile tabs

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json, packages/gatsby-theme-newrelic/src/i18n/translations/jp.json, packages/gatsby-theme-newrelic/src/i18n/translations/kr.json
`dcmaPolicy` -> `dmcaPolicy`
and
`DCMA Policy` -> `DMCA Policy`
=> Correct DMCA typo in footer and translations

demo/src/pages/index.js, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js, packages/gatsby-theme-newrelic/src/components/InlineSignup.js, packages/gatsby-theme-newrelic/src/components/MDX.js, packages/gatsby-theme-newrelic/src/components/SignupModal/RecaptchaFooter.js, packages/gatsby-theme-newrelic/src/components/SignupModal/SignupForm.js, packages/gatsby-theme-newrelic/src/components/SignupModal/signup.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json
reCaptcha doesn't work locally, so after this PR is merged i'll do a theme bump and test this on staging for the docs repo
=> create InlineSignup component

packages/gatsby-theme-newrelic/src/components/InlineSignup.js
mobile looked pretty bad. this makes it look better
=> fix InlineSignup mobile styles

.github/workflows/pr_merged.yml, .github/workflows/release-feature.yml, .github/workflows/release.yml
This way when the token needs to be rotated (like now) it's easy 🎉
=> Use org level bot token

demo/src/pages/index.js, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/Link.js, packages/gatsby-theme-newrelic/src/hooks/useLoggedIn.js
Added the LoggedInProvider to list of items being exported from the theme and added that provider to the demo page.
Updated Link component to see if urls are product URLs, if they are, and the user is not logged it, it will send them to the signup page.  If they are logged in, it will send them to the product.
=> Make Link component dynamic based on loggedIn

CONTRIBUTING.md
docs: update slack invite link NR-72269
=> docs: update slack invite link NR-72269

packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/Icon.test.js.snap, packages/gatsby-theme-newrelic/src/icons/feather.js
=> feat: add chevron left and right icons

packages/gatsby-theme-newrelic/src/components/Portal.mjs, packages/gatsby-theme-newrelic/src/components/SearchModal/SearchModal.mjs, packages/gatsby-theme-newrelic/src/components/Tabs/useTabs.mjs, packages/gatsby-theme-newrelic/src/components/__tests__/CreateIssueButton.test.mjs, packages/gatsby-theme-newrelic/src/components/__tests__/MDX.test.mjs, packages/gatsby-theme-newrelic/src/components/__tests__/SearchModal.test.mjs, packages/gatsby-theme-newrelic/src/components/__tests__/Tabs.test.mjs, packages/gatsby-theme-newrelic/src/components/__tests__/Tag.test.mjs, packages/gatsby-theme-newrelic/src/components/__tests__/Video.test.mjs, packages/gatsby-theme-newrelic/src/components/__tests__/Walkthrough.test.mjs, packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/MDX.test.mjs.snap, packages/gatsby-theme-newrelic/src/components/__tests__/sample.mdx, packages/gatsby-theme-newrelic/src/hooks/__tests__/useDarkMode.test.mjs, packages/gatsby-theme-newrelic/src/test-utils/renderHelpers.mjs, setup-test-env.mjs
Increases coverage for a handful of components. Some of these tests can definitely be tweaked or expanded upon but this is what we've got after a mini sprint 🥹
This also includes a commit from sunny's work to get the search modal/portal working in the tests
=> Increase test coverage

packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js, packages/gatsby-theme-newrelic/src/components/Lightbox.js
* fix: Add max height to images
- also provides an 'unbound' class to unset this style
* fix: images overflowing main body container
---------
=> Add max height to images (#938)

demo/gatsby-config.js, packages/gatsby-theme-newrelic/src/components/Layout/Main.js
- Adds 100% width to main layout component
- Updates global styles in theme demo to match docs site for testing
=> Add width 100% to main layout component

packages/gatsby-theme-newrelic/gatsby/on-route-update.js
* fix: add custom attributes to browser agent events
=> fix: add custom attributes to browser agent events (#999)

.github/workflows/pr_merged.yml, .github/workflows/release.yml
replaces token associated with old opensource bot user
=> Replace token name used in action workflows

demo/gatsby-config.js, packages/gatsby-theme-newrelic/package.json, yarn.lock
Update plugin to version that allows application settings to be passed to enable features like session replay
it works! https://staging.onenr.io/0xZw03Xz3Qv
=> fix: bump gatsby-plugin-newrelic

demo/src/content/steps.mdx, packages/gatsby-theme-newrelic/src/components/MarkdownContainer.js
=> feat: add new li style

packages/gatsby-theme-newrelic/src/components/Link.js, packages/gatsby-theme-newrelic/src/utils/config/i18n.js
Missed this in our first pass because we didn't have the json in yet but it wasn't updating components with the json translations
=> Add new locales to supported locales list

packages/gatsby-theme-newrelic/src/components/Link.js
Reverts newrelic/gatsby-theme-newrelic#1035
=> Revert "fix: removing extra slug portion of redirect urls"

packages/gatsby-theme-newrelic/src/components/Popover/PopoverButton.js
couple small tweaks to the PopoverButton spacing
=> fix PopoverButton spacing

packages/gatsby-theme-newrelic/src/components/SearchInput.js, packages/gatsby-theme-newrelic/src/components/SearchModal/Result.js, packages/gatsby-theme-newrelic/src/components/SearchModal/ResultList.js, packages/gatsby-theme-newrelic/src/pages/404.js
adds `position` and `searchResult` custom properties to the instrumentation of search result Links
=> update search instrumentation

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
It's time to remove this Developer link!
=> fix(Developer site): Removed Developer link in header

packages/gatsby-theme-newrelic/gatsby/on-pre-render-html.js
this is a new requirement and we're also hoping it will get rid of the osano/blocked issue on jp and kr pages
=> Use osano variant 2

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles/colors.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles/themes.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/KeyboardLegend.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/Results.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/SearchDropdown.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/Skeleton.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/index.js, packages/gatsby-theme-newrelic/src/components/SearchInput.js, packages/gatsby-theme-newrelic/src/icons/newrelic.js, packages/gatsby-theme-newrelic/src/icons/newrelic/arrow-down.js, packages/gatsby-theme-newrelic/src/icons/newrelic/arrow-go-to.js, packages/gatsby-theme-newrelic/src/icons/newrelic/arrow-up.js
this PR implements the designs for the new search experience. it has some dummy data until the functionality is implemented
- run demo site
- try search in light and dark mode
- resize to smaller screen sizes, the search should shrink as you go
- at all screen sizes, the search should look like the designs
=> new search designs

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/GlobalSearch.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/Results.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/SearchDropdown.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/Skeleton.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/index.js, packages/gatsby-theme-newrelic/src/components/SearchInput.js, packages/gatsby-theme-newrelic/src/components/SearchModal/useSearch.js, packages/gatsby-theme-newrelic/src/utils/constants.js
this PR adds functionality to the new search dropdown
- try searching for a few common search terms
- use arrow keys to navigate up and down
- try hitting enter with a recent query selected, a search selected, and with nothing selected
- try clicking results
- try resizing to mobile sizes
- hitting / focuses search from anywhere on the page
=> search redesign functionality

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/GlobalSearch.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles/colors.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles/themes.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/KeyboardLegend.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/Results.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/SearchDropdown.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/Skeleton.js, packages/gatsby-theme-newrelic/src/components/SearchDropdown/index.js, packages/gatsby-theme-newrelic/src/components/SearchInput.js, packages/gatsby-theme-newrelic/src/components/SearchModal/useSearch.js, packages/gatsby-theme-newrelic/src/icons/newrelic.js, packages/gatsby-theme-newrelic/src/icons/newrelic/arrow-down.js, packages/gatsby-theme-newrelic/src/icons/newrelic/arrow-go-to.js, packages/gatsby-theme-newrelic/src/icons/newrelic/arrow-up.js, packages/gatsby-theme-newrelic/src/utils/constants.js
this replaces the old search experience with the redesign
=> feat: search redesign

package.json
the linter always fails on main complaining about imports that aren't a real issue, this is an attempt to fix that
=> Try skipping lerna cache

.github/workflows/release.yml
this should turn off branch protection and then add back the pull request requirement with no review required
=> Disable branch protection for publish
