newrelic/gatsby-theme-newrelic

README.md
Adds navigation for the README, documentation for the options and documentation for the components. Will be added to as we add more components. 
closes #6
=> Documentation for API and configuration

packages/gatsby-theme-newrelic/package.json
Add the `keywords` field to `package.json` to make it more discoverable, and prepare the package for sharing on Gatsby's website.
=> Add keywords to package.json

README.md, packages/gatsby-theme-newrelic/README.md
Adds documentation for all APIs available for the theme. Moves the majority of the documentation to the `gatsby-theme-newrelic` package README so that it can be published to npm.
=> Add all component and hook documentation

.github/workflows/release.yml
Fixes [failing lerna publish action](https://github.com/newrelic/gatsby-theme-newrelic/runs/919890194?check_suite_focus=true) which expects a `GH_TOKEN` environment variable.
=> Update GitHub token env var name

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/Surface.js
The `Surface` component has an `interactive` prop that can be toggled to add interactive styling to the surface. This PR adds the documentation and prop type for that prop.
[Rendered](https://github.com/newrelic/gatsby-theme-newrelic/tree/jerel/document-interactive-prop/packages/gatsby-theme-newrelic)
=> Document interactive prop

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
Prevent Swiftype from indexing the global header content as part of the page content.
=> Don't index the global header with swiftype

README.md
Adds the support link to Explorer's hub for the project to the README
[Rendered](https://github.com/newrelic/gatsby-theme-newrelic/blob/jerel/support-thread/README.md)
=> Add support link to explorers hub

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/package.json, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js, packages/gatsby-theme-newrelic/src/hooks/useQueryParams.js, packages/gatsby-theme-newrelic/src/styles/SwiftypeSearchStyles.js
This PR addresses the issue where pressing the "enter" key after searching would result in a 404 page due to how the page would navigate. This PR also fixes the double scroll issue in the search overlay when looking at a page of results.
=> Fix issues when pressing "enter" key while searching

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/Button.js, packages/gatsby-theme-newrelic/src/components/CodeBlock.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles.js, packages/gatsby-theme-newrelic/src/components/HamburgerMenu.js, packages/gatsby-theme-newrelic/src/components/Surface.js, packages/gatsby-theme-newrelic/src/components/Tag.js, packages/gatsby-theme-newrelic/src/icons/feather.js
Closes https://github.com/newrelic/developer-website/issues/536
Closes #75 
Closes #79 
Adds a sign up button to the global header. Also addresses the following:
* Improves the mobile view of the global header by adding a horizontal scroll to the site links
* Adds a full brand color palette
* Adds hover states to buttons
* Deprecates the `Plain` button in favor of a `Link` style button
=> Add a sign up button + other minor global header improvements

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
Spacing between the search, dark mode, and sign up buttons should be a uniform 16px.
Issue: https://github.com/newrelic/developer-website/issues/629
Before:
After:
=> fix: make spacing between sign up and dark mode uniform

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
Issue: https://github.com/newrelic/developer-website/issues/629
@jpvajda and I agree that the icon doesn't really add a lot to the sign up button so we're nixing it for now.
=> fix: remove cloud icon from sign up button

packages/gatsby-theme-newrelic/src/components/Overlay.js, packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/GlobalHeader.test.js.snap
This bumps the z-index on the `Overlay` component to ensure it sits on top of all the other content. This will fix some of the issues on the OSS site by adhering to the [newly proposed z-index scale](https://github.com/newrelic/opensource-website/pull/608#issuecomment-676723812).
=> Update z-index on overlay

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/Button.js, packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/GlobalHeader.test.js.snap
Adds an `outline` button variant
=> Add an "outline" button variant

packages/gatsby-theme-newrelic/src/utils/getSplitConfig.js
Environment-specific options were being resolved to `development` incorrectly when configuration for an environment was not specified. This PR ensures that the resolved configuration for an environment does not fall back to `development` if environment-specific settings are not specified for the given environment.
=> Do not fall back to development settings when resolving split.io env options

package.json, packages/gatsby-theme-newrelic/src/components/FeatherSVG.js, packages/gatsby-theme-newrelic/src/components/Icon.js, packages/gatsby-theme-newrelic/src/components/SVG.js, packages/gatsby-theme-newrelic/src/components/__tests__/Icon.test.js, packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/GlobalHeader.test.js.snap, packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/Icon.test.js.snap, setup-test-env.js, yarn.lock
In some cases, we may want to render icons with a gradient for its stroke, for example with the icons on the new Nerd Days event page. This adds the ability to specify `<defs />` on the svg that can be used to define gradients.
=> Add ability to specify icon defs

.github/workflows/release.yml, packages/gatsby-theme-newrelic/src/components/AnnouncementBanner.js
This PR fixes an issue where `btoa` is not available when Gatsby builds a site using this theme.
Additionally, this adds a step to our `release` workflow that attempts to build the site. This allows us to catch any issues in the theme that would break a build for a site that uses it.
=> Fixes for Gatsby Build

packages/gatsby-theme-newrelic/src/components/AnnouncementBanner.js
I believe that this is happening because there is a swifttype index on the Banner for the annoucement banner and we're returning that, even though there is null being returned from the actual Banner. 
By adding this conditional, I think we will solve the problem and fully remove the banner and it's index
=> Doesn't return banner with swifttype index when not visible

packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/AnnouncementBanner.js, packages/gatsby-theme-newrelic/src/hooks/useHasMounted.js
Read more about [this solution](https://joshwcomeau.com/react/the-perils-of-rehydration/) here. 
Our conditional rendering of the announcement banner was causing a rehydration issue that was leading to a mismatch between our client side rendering and SSR.
=> Only renders the announcement banner after the component has mounted

packages/gatsby-theme-newrelic/src/components/AnnouncementBanner.js
When the user dismisses an announcement banner, a hash is stored in local storage that tracks that it was the last banner dismissed. If a user comes back to the site, it _should_ not be displayed.
Here's an example of the current banner hash in my browser and it's contents:
```js
const hash = "M2I3MjgzMDItYjZiNC01YWI5LWIzOWUtMDk5YWEyYTdjZTRiOjIwMjAtMDktMTU6MjAyMC0xMC0wMg==";
console.log(atob(hash));
// "3b728302-b6b4-5ab9-b39e-099aa2a7ce4b:2020-09-15:2020-10-02"
// format -> id:start:end
```
This was not working. I suspect this is because part of the hash is the banner `id` and that may be changing when we rebuild the site. This change updates that logic to use the banner `slug` instead (the filename without extension). I think this should resolve the issue.
=> Fix issue with banners not dismissing

packages/gatsby-theme-newrelic/README.md
Replaced erroneous `</Button>` with `</Callout>` in Callout > Examples section
=> Fix typo in README doc re: Callout component

packages/gatsby-theme-newrelic/src/components/CodeHighlight.js
Some minor adjustments to the code block:
* Lightens the background color on the line highlighting to contrast with the
text a bit better
* Stop covering the line numbers with the line highlighting
**Before**
**After**
=> Minor code block enhancements

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/Callout.js
* Adjusts the spacing on the callout by removing the horizontal spacing. 
* Ensure the title's top-margin is always removed
* Allow the user to disable the title completely
=> Minor callout adjustments

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, yarn.lock
Closes https://github.com/newrelic/docs-website/issues/171
Adds a login link to the global header. Reorders the nav links to correspond to the suggested order. Removes split.io links from the header.
=> Add login link to global header

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js, packages/gatsby-theme-newrelic/src/components/Logo.js
Use the New Relic Logo as the default logo implementation. Add responsive styles for the footer and ensure the width is set on the logo.
=> Minor footer improvements

packages/gatsby-theme-newrelic/gatsby/on-pre-render-html.js
Fix the missing key warning on the head element when starting up a gatsby site
=> Fix missing key warning on head element

packages/gatsby-theme-newrelic/gatsby-node.js
In all of our sites, we configure an "edit this page" link using a file relative path field. This PR adds that logic to the theme so that each site does not have to implement it.
=> Automatically add fileRelativePath to mdx nodes and pages

demo/gatsby-config.js, demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/ContributingGuidelines.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles.js, packages/gatsby-theme-newrelic/src/components/PageTools/PageTools.js, packages/gatsby-theme-newrelic/src/components/PageTools/Section.js, packages/gatsby-theme-newrelic/src/components/PageTools/Title.js, packages/gatsby-theme-newrelic/src/components/PageTools/index.js
Closes #144 
Adds a `PageTools` component that can be leveraged to show content as a "right rail" for each Gatsby site. This also includes some building blocks as well as a `ContributingGuidelines` component that can be used to display information on how to edit the current page/file an issue/link to contributing guidelines.
=> "Right rail" component

packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js
We filter out menu pages by default because they're just lists of links to other pages, so they add a lot of noise to docs search results.
We add each docs page's content type in the swiftype field `document_type`
Example of a menu page: https://docs.newrelic.com/docs/apm/apm-ui-pages/monitoring
=> Filter out menu pages for docs results

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js
This PR adds the careers link to the global footer
=> fix: added career link to global footer

packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js
Closes #84 
This fixes the issue described in issue linked above. When search overlay opens it focuses the search input so a user can start typing.
We had to put it in a `setTimeout()` in order to wait out whatever was happening with `<Overlay />` component rendering. The CSS transitions that run on open took ~500ms. 100ms seemed to do the trick for the timeout though ¯\_(ツ)_/¯
=> Focus search input when overlay opens

demo/src/pages/index.js, package.json, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/SimpleFeedback.js, packages/gatsby-theme-newrelic/src/components/__tests__/SimpleFeedback.test.js
Adds the [`<SimpleFeedback />`](https://github.com/newrelic/docs-website/pull/412) component to the theme so that multiple sites can make use of it. Clicking one of the sentiment buttons will open up a new browser tab and take the user to the new issue screen. Depending on the props provided, different elements will be pre-filled and special labels are applied.
I also added some tests for this component, since there are a few different states the component can be in that are easily testable. I also wanted to provide us with an example of how to mock `useStaticQuery` and `graphql` from Gatsby.
=> Added a `<SimpleFeedback />` Component

packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js
Reverts newrelic/gatsby-theme-newrelic#154
For some reason, this PR is causing sites to constantly refresh themselves. Until we have the time to sort this out, I'd like to revert this work.
=> Revert "Focus search input when overlay opens"

packages/gatsby-theme-newrelic/gatsby-node.js
When sourcing nodes, add a `fileRelativePath` to `MarkdownRemark` nodes in addition to `Mdx` nodes.
=> Add a fileRelativePath field to MarkdownRemark nodes

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/package.json, packages/gatsby-theme-newrelic/src/components/CodeBlock.js, packages/gatsby-theme-newrelic/src/components/MDXCodeBlock.js, packages/gatsby-theme-newrelic/src/components/Terminal/CommandLine.js, packages/gatsby-theme-newrelic/src/components/Terminal/MenuBar.js, packages/gatsby-theme-newrelic/src/components/Terminal/Prompt.js, packages/gatsby-theme-newrelic/src/components/Terminal/Shell.js, packages/gatsby-theme-newrelic/src/components/Terminal/ShellOutput.js, packages/gatsby-theme-newrelic/src/components/Terminal/Terminal.js, packages/gatsby-theme-newrelic/src/components/Terminal/gaussianRound.js, packages/gatsby-theme-newrelic/src/components/Terminal/index.js, packages/gatsby-theme-newrelic/src/components/Terminal/machine.js, packages/gatsby-theme-newrelic/src/components/Terminal/theme.js, packages/gatsby-theme-newrelic/src/components/Terminal/utils/collapseLine.js, packages/gatsby-theme-newrelic/src/components/Terminal/utils/translateLines.js, packages/gatsby-theme-newrelic/src/hooks/useFormattedCode.js, packages/gatsby-theme-newrelic/src/utils/codeBlock.js, packages/gatsby-theme-newrelic/src/utils/formatCode.js, yarn.lock
Brings over the `Terminal` component from the docs site into the theme! This will allow us to use it on all sites when rendering shell content. On top of the `Terminal` component, this PR does the following:
* Adds sass/scss syntax highlighting support out of the box
* Adds the ability to turn off auto code formatting on code blocks
* Default enables auto code formatting on a subset of languages, rather than trying to format text in every code block (addresses https://github.com/newrelic/developer-website/issues/222)
* Adds code formatting support for more languages
* Auto detects the prettier parser that should be used based on the language
=> Add the terminal component + code block improvements

packages/gatsby-theme-newrelic/src/components/Link.js
Ensures that anchor links (links that start with `#`, such as the links generated from `gatsby-remark-autolink-headers`) are treated the same as relative links. Currently they are treated the same as an external link, which opens the link in a new tab.
=> Ensure anchor links are treated the same as relative links

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
this PR adds logic to the sign up button to show sign up text when on the docs site domains, and start now text on all other domains.  To test you can use `window.location.href` as `window.location.hostname` doesn't work on localhost URLS.
```
//testing
const domain = window.location.href;
console.log(window.location.href);
{domain === 'http://localhost:8001/' ||
domain === 'http://localhost:8001/build-apps'
? 'Sign Up'
: 'Start Now'}
```
=> feat: added signup button logic

packages/gatsby-theme-newrelic/src/components/MDXCodeBlock.js
With the recent change to the `MDXCodeBlock` component to automatically render terminals for shell languages, it appears I forgot to call the function :facepalm:, which means that all code blocks inside of an MDX document are rendering as a terminal. This PR ensures the terminal is rendered conditionally.
=> Fix auto terminals in MDX code blocks

demo/gatsby-config.js, packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/src/components/Button.js, packages/gatsby-theme-newrelic/src/components/Dropdown/Context.js, packages/gatsby-theme-newrelic/src/components/Dropdown/Dropdown.js, packages/gatsby-theme-newrelic/src/components/Dropdown/Menu.js, packages/gatsby-theme-newrelic/src/components/Dropdown/MenuItem.js, packages/gatsby-theme-newrelic/src/components/Dropdown/Toggle.js, packages/gatsby-theme-newrelic/src/components/Dropdown/index.js, packages/gatsby-theme-newrelic/src/components/Dropdown/useDropdown.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
Closes #181
Adds a language toggle to the global header. This PR also adds the ability to configure additional locales supported for the sites. This will automatically create a route for each page in src/routes with a link to the localized route.
=> Add language toggle in the global header + i18n config options

packages/gatsby-theme-newrelic/gatsby-node.js
Unfortunately the hook that tries to create pages for all locales is not working right. This PR disables that behavior until we can get something working.
=> Do not automatically create pages for additional locales

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/Dropdown/Dropdown.js, packages/gatsby-theme-newrelic/src/components/Dropdown/Toggle.js
Adds the internationalization documentation for the theme settings and documents how to use the dropdown components (including the sub-components).
This documentation covers the work done in #187
I marked two props a `isRequired`:
* `children` for the `<Dropdown />` component - doesn't make sense to render a dropdown without a toggle or menu
* `variant` for the `<Dropdown.Toggle />` component - it's required by the underlying `<Button />` component
We might want to consider a default `variant` on the button so that we can remove the requirement on this component. Either way, it's outside fo the scope of this PR.
=> Documentation for `i18n` settings and the `<Dropdown />` component

packages/gatsby-theme-newrelic/gatsby-node.js
When I brought the plugin for sourcing swiftype into the theme itself, I forgot to update all references of `pluginOptions` -> `themeOptions` (#201). This PR updates that and ensures we're using a consistent variable name throughout `gatstby-node.js`.
=> Update `pluginOptions` -> `themeOptions`

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/gatsby-config.js, packages/gatsby-theme-newrelic/src/components/GlobalFooter.js
Closes #214
Closes #215
Adds the ability to disable sitemaps with the `sitemap: false` option in `gatsby-config.js`. Also removes the GitHub buttons in the footer if the `repository` is not configured
=> Configurable sitemaps + GH buttons

packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js
Adds additional global styles for the anchor icon next to headings provided by `gatsby-plugin-autolink-headers`.
=> Add styles for anchor icon next to autolinked headers

packages/gatsby-theme-newrelic/src/i18n/translations/en.json
The copyright date was updated in #222, but because the footer is translated, the translation also needed to be updated. This PR ensures the translation is up-to-date.
=> Fix copyright date

packages/gatsby-theme-newrelic/src/components/SearchInput.js
Fixes the following warning:
```
Functions that are interpolated in css calls will be stringified.
If you want to have a css call based on props, create a function that returns a css call like this
let dynamicStyle = (props) => css`color: ${props.color}`
It can be called directly with props or interpolated in a styled call like this
let SomeComponent = styled('div')`${dynamicStyle}`
```
=> fix emotion warning about stringified function

packages/gatsby-theme-newrelic/src/components/Table.js
With the recent update to the `<Table>` component to make it scrollable, the `className` was not moved to the outer container. This creates a problem with the `MDXTable` component when trying to add spacing since it does not apply the proper element.
=> Add className to outer wrapper

demo/src/pages/build-apps/build-hello-world-app.mdx, demo/src/templates/basic.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/gatsby/type-defs.graphql, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/RelatedResources.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json, packages/gatsby-theme-newrelic/src/utils/defaultOptions.js, packages/gatsby-theme-newrelic/src/utils/related-resources/createRelatedResourceNode.js, packages/gatsby-theme-newrelic/src/utils/related-resources/fetchRelatedResources.js, packages/gatsby-theme-newrelic/src/utils/related-resources/search.js
Relates to https://github.com/newrelic/docs-website/issues/427
[README updates](https://github.com/newrelic/gatsby-theme-newrelic/tree/jerel/related-resources/packages/gatsby-theme-newrelic)
Adds a `RelatedResources` component that can be used in the right rail of the site.
This PR also makes some tweaks to the related resource configuration. The theme now provides the related resources framework without the need to enable Swiftype. Out-of-the-box, related resources will now be sourced from frontmatter for all non-announcement `Mdx` nodes. The swiftype configuration has now been moved to the `relatedResources` config.
Some additional features worthy of mention:
* Force disable refetching in development mode. Will now show a warning if `refetch` is set to try and you run `gatsby develop`. …
=> Related resource component + tweaks

demo/gatsby-config.js, demo/src/pages/build-apps/build-hello-world-app.mdx, demo/src/templates/basic.js, packages/gatsby-theme-newrelic/src/components/Button.js, packages/gatsby-theme-newrelic/src/components/Dropdown/MenuItem.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/GlobalNavLink.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles/themes.js, packages/gatsby-theme-newrelic/src/components/MarkdownContainer.js, packages/gatsby-theme-newrelic/src/components/NavLink.js, packages/gatsby-theme-newrelic/src/components/Surface.js, packages/gatsby-theme-newrelic/src/components/Tag.js
* Add a small border radius around images to make them feel more like they are
part of the page
* Links now use text decoration. We had some feedback that links were difficult
to decipher for colorblind folks. Talking with @djsauble, we decided that
adding text decoration to links was a good move.
=> Minor image + link style changes

packages/gatsby-theme-newrelic/src/components/ContributingGuidelines.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json
This PR changes the contributor CTA in the right rail. 
Closes: https://github.com/newrelic/docs-website/issues/753
=> chore: updated contributor CTA message

packages/gatsby-theme-newrelic/src/components/Collapser.js, packages/gatsby-theme-newrelic/src/components/__tests__/Collapser.test.js
Closes [docs-website/795](https://github.com/newrelic/docs-website/issues/795)
Adds support for opening all collapsers via query param: `collapsers=openAll`. This is particularly useful when uploading contexts to Smartling so all content is visible to translators.
=> Add support for opening all collapsers via query param

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/hooks/__tests__/useInstrumentedHandler.js, packages/gatsby-theme-newrelic/src/hooks/useInstrumentedHandler.js
Adds a `useInstrumentedHandler` hook to easily augment handlers with `newrelic.addPageAction` calls.
=> Add a useInstrumentedHandler hook

packages/gatsby-theme-newrelic/src/components/GitHubIssueButton.js, packages/gatsby-theme-newrelic/src/components/SimpleFeedback.js
Related to https://github.com/newrelic/docs-website/pull/900 .
This PR simplifies the copy for GH issues resulting from yes/no button clicks.
**Reviewer notes**
This line in SimpleFeedback.js
```  const issueTitle = pageTitle ? `Feedback: ${pageTitle}` : 'Docs feedback';```
Seems to imply that the issue title will include the page title (which would be helpful in scanning issues). But the code doesn't seem to actually be working, at least on docs-preview.newrelic.com
=> Simplify yes/no GH issue template copy

packages/gatsby-theme-newrelic/src/utils/page-tracking/tessen.js
The theme contains an error when booting up the site due to a reference to an undefined variable. This PR fixes the reference to that variable.
=> Fix reference to undefined variable

packages/gatsby-theme-newrelic/src/components/ResultView.js, packages/gatsby-theme-newrelic/src/styles/SwiftypeSearchStyles.js
Closes https://github.com/newrelic/docs-website/issues/917
Minor styling touchups to remove the large amount of space between search
results. Also updates some styles to ensure the font is using the same font
family as the rest of the site.
=> Minor touchups to search

packages/gatsby-theme-newrelic/src/hooks/__tests__/useKeyPress.js, packages/gatsby-theme-newrelic/src/hooks/useKeyPress.js
`useKeyPress` currently lowercases the keys passed to the handler before it checks if a match occurs. For most key presses, this is fine, but for some, casing matter. This PR ensures casing is maintained so that matches against keys like `ArrowUp` or `ArrowDown` function as expected.
=> Care about casing on key press events

packages/gatsby-theme-newrelic/src/components/Table.js
Closes https://github.com/newrelic/docs-website/issues/879
We've had a good amount of feedback about the table cell alignment and wanting that vertically aligned to the top. This PR updates the table component to vertically align cells to the top.
**Before**
**After**
=> fix(Table): Vertically align the text in cells to the top of the cell instead of the center

demo/gatsby-config.js, packages/gatsby-theme-newrelic/src/components/CookieConsentDialog.js
When loading our sites, the cookie consent dialog will show briefly before disappearing when a user has accepted cookies. The flash of content is less than ideal. This PR ensures the cookie consent is only shown once the component has rendered on the client to prevent that flash.
=> Don't show cookie consent until the client has rendered

packages/gatsby-theme-newrelic/src/components/CreateIssueButton.js, packages/gatsby-theme-newrelic/src/components/GitHubIssueButton.js
Partially addresses https://github.com/newrelic/docs-website/issues/1096
Removes the duplicate "Doc information" heading when clicking on the "Create issue" button.
=> Remove duplicate doc information heading

packages/gatsby-theme-newrelic/src/components/MarkdownContainer.js
~~@jerelmiller Though this could impact lists that expect a margin... ;-)~~
Edit: as requested now only changes the `MarkdownContainer` styles for this list style issue
fixes https://github.com/newrelic/docs-website/issues/945
https://github.com/newrelic/docs-website/pull/1110
=> fix: li>p element should not have a bottom margin

packages/gatsby-theme-newrelic/src/components/NavItem.js
fixes https://github.com/newrelic/docs-website/issues/938
cases (demo app):
* Nav search for "relic" displays all items containing "relic" and the collapse works
* Then search "data" displays all items containing "data" (previous collapsed are no longer collapsed) and the collapse works
=> fix(nav): on search the item collapse should work

packages/gatsby-theme-newrelic/src/components/SearchInput.js
fixes https://github.com/newrelic/docs-website/issues/937
Type "test" in the global search
Click the "x"... global search is cleared (previously was not)
=> fix(global-search): when cancelling a search the search input is cleared

packages/gatsby-theme-newrelic/src/components/SearchInput.js
While solving a few other search-component issues I noticed that the search component had invalid css;
* Well the IDE said it is invalid css.. and I know that it is.
* Bad CI linting
* Someone editing in notepad?
* Someone editing in notepad?
=> fix(search): invalid css

packages/gatsby-theme-newrelic/src/components/ExternalLink.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/Link.js, packages/gatsby-theme-newrelic/src/components/__tests__/CodeBlock.test.js, packages/gatsby-theme-newrelic/src/components/__tests__/SimpleFeedback.test.js, packages/gatsby-theme-newrelic/src/test-utils/renderHelpers.js
tested it by console logging the event (because there was a no-op due to tessen not being configured for the demo site. Tracks when you click signup buttons, but not when you click a regular old external link. 
Also uses the external link component instead of `a` tag to separate actions for external links and links in general. 
Addresses https://github.com/newrelic/docs-website/issues/1113 once the theme is updated
=> Tracks tessen for sign up links and allows to specify additional props to the event

packages/gatsby-theme-newrelic/src/utils/page-tracking/tessen.js
We were not recording updates on our pages because we were initialize tessen a bunch of times. As a result, we were initializing Segment and NR a bunch of times as well, which let to downstream errors that prevented us from recording our data. This should ensure that we only call initialize once!
=> Initializes tessen only once

packages/gatsby-theme-newrelic/src/components/__tests__/Link.test.js, packages/gatsby-theme-newrelic/src/utils/location.js
Ensures links to locations with an extension (i.e. `.json`, `.xml`) do not add a trailing slash, even if `forceTrailingSlashes` is configured. This fixes the RSS feed links for release notes on the docs site.
=> Do not add trailing slash to links with extension

packages/gatsby-theme-newrelic/src/components/ContributingGuidelines.js
Relates to https://github.com/newrelic/docs-website/issues/1206
We added the ability to make `issues` a prop to our `CreateIssueButton` component (#311), but we forgot that the component is used inside of `ContributingGuidelines`. This PR adds a prop to forward to `CreateIssueButton` so that we can override the labels for the create issue button.
=> Add an issueLabels prop to forward to CreateIssueButton

packages/gatsby-theme-newrelic/src/components/SEO.js
Adds some logic to `<SEO />` component to get New Relic subdomain value from `siteMetaData.siteUrl` and the locale of the page if it's not the default (so any language other than English) and set the swiftype `type` field. Those values are currently set to the subdomain value in the Swiftype index.
Does not generate the meta tag if not on a New Relic subdomain (ex: localhost)
This requires opensource, docs, and developer sites to remove the code they use to generate the `type` field.
Docs site (English)
<meta class="swiftype" name="type" data-type="enum" content="docs">
Docs site (Japanese)
<meta class="swiftype" name="type" data-type="enum" content="docs-jp">
- https://github.com/newrelic/docs-website/issues/1204
=> Add swiftype type field for all NR subdomains

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js
This PR adds an issueLabels prop to the global footer so we can define the type of label that is attached to an issue when a user clicks create issue on the Docs Site. Given the changes implemented here:
https://github.com/newrelic/docs-website/issues/1206
I think this will just `work` after this is merged and we bump the theme on the docs site. 🤞
=> chore: adds issuelabel prop to global footer

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/SwiftypeSearch.js
This work updates swiftype search to switch the filters on `type` (distinguishes what site the page belongs to) based on the locale context. If a user is on the default locale of the site (English), it filters for the standard types (docs, developer, opensource). If a user is on a locale namespaced page (ex: https:docs.newrelic.com/jp/docs/agents) and uses search, it will filter for those locale pages in the index. 
This also adds a filter to exclude `views_page_content` for now (attribute dictionary and whats new page) because those pages tend to add noise like menu pages (because they are lists / links of content that lives and is indexed separately).
**Note**: All locale namespaced pages automatically get the localized meta tag `type` via the theme. If a namespaced page only has …
=> Support search for locale pages with translated content

packages/gatsby-theme-newrelic/src/utils/createTessen.js
Adds 3rd arg to any `tessen.page()` and `tessen.track()` calls to enable all Segment integrations by default.
We can also control what integrations/destinations are enabled/disabled in the Segment UI.
=> Tessen: Enable all Segment integrations by default

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/Callout.js, packages/gatsby-theme-newrelic/src/components/GlobalStyles/themes.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json
This adds a variant to the callout component for `course`
Addresses https://github.com/newrelic/developer-website/issues/1239 but can't be considered fully done until we have the Japanese translation for course. While the current use case for this callout is on the developer site, it's possible we'd want to use it to link to a guide from the docs site, etc.
=> Add course callout variant

demo/gatsby-config.js, packages/gatsby-theme-newrelic/gatsby-node.js
This resolves the bug found when trying to bump the theme on the dev and oss sites 
```
SiteSiteMetadata.utmSource provided incorrect OutputType: 'Object({
resolve: [function wrappedTracingResolver], extensions: Object({
createdFrom: "createResolvers" }) })'
Error: SiteSiteMetadata.utmSource provided incorrect OutputType: 'Ob
ject({ resolve: [function wrappedTracingResolve
```
Related PRS: 
https://github.com/newrelic/opensource-website/pull/749
https://github.com/newrelic/developer-website/pull/1254
=> chore: remove utmsource from gatsby-config

packages/gatsby-theme-newrelic/src/components/SignUpLink.js, packages/gatsby-theme-newrelic/src/components/__tests__/Link.test.js
The `referrer` field was not being sent when a user clicks the `free account` button on our sites. This was caused by the `rel="noreferrer"` property on our the SignUpLink component.
The `noreferrer` and `noopener` types control the information passed to the new tab. The former prevents referrer information from being passed to the new tab and the latter prevents a lot of other information from being passed.
We have 2 main options to fix this:
1. Remove the `noreferrer` type (possible security risk, but we do own the site we are linking to)
2. Do not open the link in a new tab
This PR currently fixes this issue through option 1.
=> Fix referral field not being sent to analytics

demo/gatsby-config.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/SplitColorButton.js, packages/gatsby-theme-newrelic/src/components/__tests__/SplitColorButton.test.js, packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/SplitColorButton.test.js.snap, packages/gatsby-theme-newrelic/src/utils/constants.js
Adds a `SplitColorButton` component that wraps the `Button` component and overrides the `background-color` according to a split in Split.io.
Example:
https://user-images.githubusercontent.com/70179303/116735081-e7948b00-a9a2-11eb-9432-9f664a2a6fa2.mov
=> Add SplitColorButton

packages/gatsby-theme-newrelic/src/components/CookieConsentDialog.js
Records when a user selects Yes in the `<CookieConsentDialog />`. Records via New Relic Browser `PageAction` event.
Closes https://github.com/newrelic/docs-website/issues/1507
Example query:
```
SELECT * FROM PageAction where appName = 'New Relic Gatsby Theme - Demo site' and actionName = 'cookieConsent' and agree is true since 3 days ago
```
=> Track when users agree to cookie usage

packages/gatsby-theme-newrelic/src/utils/createTessen.js
Gets the value of `ajs_user_id` if available and sends along with all `tessen.page()` and `tessen.track()` calls. If no value available, sends empty string.
Note: we only use tessen when a user has agreed to cookie usage.
Testing is a little tricky since the `ajs_user_id` cookie is set to newrelic domains. Need to verify once one of the sites incorporates it. I tested locally with `ajs_anonymous_id` and it did work.
Closes https://github.com/newrelic/docs-website/issues/1668
=> Add `customer_user_id` in all tessen calls

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/SplitColorButton.js, packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/SplitColorButton.test.js.snap, packages/gatsby-theme-newrelic/src/utils/constants.js
This PR builds (fixes my mistake) on https://github.com/newrelic/gatsby-theme-newrelic/pull/377 to add event tracking when a user clicks on the button.
Related issue: https://github.com/newrelic/gatsby-theme-newrelic/issues/356
=> Properly track track click events within a Split.io segment

packages/gatsby-theme-newrelic/gatsby-config.js, packages/gatsby-theme-newrelic/package.json, yarn.lock
Updates `gatsby-plugin-sitemap` version and explicitly sets the output path in the demo config.
Closes https://github.com/newrelic/docs-website/issues/2103
=> Fix sitemap output

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
This PR adds the learn URL to the global header.
=> chore: adds learn link to global header

packages/gatsby-theme-newrelic/src/components/Link.js
Closes #390
Fix the link styles for anything using the `Link` component. The `className` was not properly forwarded.
**Before**
**After**
=> Fix styles on Link component

packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js
Partially addresses https://github.com/newrelic/docs-website/issues/1138
This adds `white-space: pre-wrap` to code blocks. if a line is exceeding the width of the container it will automatically wrap. I haven't noticed any issues with this other than it looking a bit odd with long comments. comments that auto wrap don't have comment syntax on each line (like: `//first line` `//second line`) but they still copy/paste in the correct format
also thank you to hero @nr-kkenney 🏆
=> Add whitespace wrap to code blocks

packages/gatsby-theme-newrelic/src/components/Link.js
A fix that allows us to set the innerHTML for links. This is necessary to resolve an issue with the search results not showing link text.
=> Fixing search result links

packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js, packages/gatsby-theme-newrelic/src/components/Link.js
Bring in a fix for search result links (and the commits below).
- feat(tessen): add customer id via segment cookie with all tessen calls
- feat(analytics): track when users agree to cookie usage
- refactor: separate tessen and newrelic blocks
- fix(sitemap): update sitemap plugin version and explicitly set output path
- fix: add proper split.io tracking
- fix: only adding valid props to anchor tags
- fix: add 'env' to tessen call
- chore: using `first-of-type` to suppress warnings
- chore: only use _layout_ effects when we have access to window
- chore: ensuring that keys are unique
- chore: adds learn link to global header
- Revert "chore: using `first-of-type` to suppress warnings"
- fix: ensuring that link text is present
- fix: added `role` to the acceptable attributes for a link
- …
=> Release fix for search links

packages/gatsby-theme-newrelic/src/components/SimpleFeedback.js, packages/gatsby-theme-newrelic/src/components/__tests__/SimpleFeedback.test.js
This removes the functionality of opening an issue upon leaving feedback. It also adds tessen tracking for positive or negative responses and displays a message after clicking to prevent spamming (unless you're determined and reload the page a lot)
Closes https://github.com/newrelic/gatsby-theme-newrelic/issues/373
=> Update feedback component functionality and tracking

packages/gatsby-theme-newrelic/src/components/SearchModal/SearchModal.js
On PR review for opensource, there are some elements that have a 300 z-index, causing to float over the search modal. This bumps z-index up much higher to avoid that since it needs to float over most things.
https://github.com/newrelic/opensource-website/pull/784
=> Fix: Bump SearchModal z-index up higher

packages/gatsby-theme-newrelic/src/components/Link.js
Adds a check for the class that the `gatsby-remark-images` plugin adds to `<a>` tags that wrap images and returns straight up `<a>` instead of a Gatsby `<Link />` component.
Since we're explicitly using `className` now, had to set that explicitly in all returns otherwise it does not get passed via `...props`
https://user-images.githubusercontent.com/2952843/119009206-bd9e0b00-b947-11eb-8457-fb0f45d1e2c8.mp4
https://github.com/newrelic/docs-website/issues/2363
=> Fix to open image links in new tab

packages/gatsby-theme-newrelic/gatsby/on-client-entry.js, packages/gatsby-theme-newrelic/package.json, packages/gatsby-theme-newrelic/src/components/AnnouncementBanner.js, packages/gatsby-theme-newrelic/src/components/DarkModeToggle.js, packages/gatsby-theme-newrelic/src/hooks/__tests__/useUserId.test.js, packages/gatsby-theme-newrelic/src/hooks/useUserId.js, packages/gatsby-theme-newrelic/src/utils/isLocalStorageAvailable.js, yarn.lock
* Remove direct interaction with local storage in useUserId and use
`use-local-storage-state`
* Replace use of `use-persisted-state` in the AnnouncementBanner with
`use-local-storage-state`
* `on-client-entry.js` add check for local storage before accessing it
* Add check for local storage and in-memory store to DarkModeToggle
* Uses of `use-persisted-state` were removed because the library does
not have a fallback if local storage is unavailable
=> fix: handle lack of access to local storage

packages/gatsby-theme-newrelic/src/components/SearchModal/search.js
Removes the weighting fields and lets the swiftype admin UI setting apply instead.
Closes https://github.com/newrelic/docs-website/issues/2455
=> Improve search results by removing field weights

packages/gatsby-theme-newrelic/src/components/DarkModeToggle.js
Remove mocked localStorage since it causes issues on the Docs site. Passing in `false` causes `useDarkMode` to default to a React hook instead.
=> fix: remove mocked storage and use built in option

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
* added a pageaction to track user terms in the globalheader since that
has a debounce hook. this should enable search terms data populating our
dashboard again.
Relates to: https://github.com/newrelic/docs-website/issues/2598
=> fix: add pageaction to track user search terms

packages/gatsby-theme-newrelic/src/utils/page-tracking/tessen.js
Tessen is seemingly not capturing most referrer URL paths if a user has loaded the site and then clicks on any links for other pages on the site. We can explicitly set that, because we already send a "pageview" event for each route change. This just adds a `referrer` value to the `properties` in the tessen payload.
Also includes remove superfluous `location.pathname` since that's captured via `gatsby-config.js` properties function. Also, it seems `location` is used by tessen to indicate it's a `Public` site, so it was being overridden anyway.
Related to https://github.com/newrelic/docs-website/issues/2841
=> Explicilty set referrer URL path for Tessen

packages/gatsby-theme-newrelic/gatsby-node.js
`path.join` is platform-dependent: it uses backslashes as separators on Windows.
So pages generated with this theme have incorrect URLs.
=> Generate correct path on Windows

packages/gatsby-theme-newrelic/src/components/SEO.js
Adds a type prop so we can override the regular path of using the subdomain and use `quickstarts` from within the dev site
=> Add type prop to SEO component

packages/gatsby-theme-newrelic/src/components/Overlay.js
Passes className to the top level div of the overlay. Currently the overlay is opaque, but we have a use case for transparent which this change will allow
=> Pass className to Overlay

packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/GlobalNavLink.js
Adds some extra flexibility to our `<GlobalHeader />` component so that we can custom-set which page we would like to show as "active" (the one with a background color). We can use this code to update specific pages on the developer website to highlight "Instant Observability".
This PR also moves the storage of the links to an array so that, if we need to change the order / items, we only have to update it in one location (rather than a few places in the JSX).
This PR is an alternative approach compared to solving #438 (compared to #449). I don't mind which direction we go, just wanted to move the conversation forward.
=> Add ability to custom-set active sites in `<GlobalHeader />`

packages/gatsby-theme-newrelic/src/components/SearchModal/NoResults.js
This PR replaces the no results message with the approved language.
=> chore: fixed no results text

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
Simply removes the I/O nav item in the `GlobalHeader` so we can continue non-IO theme releases
=> Remove IO from header nav

packages/gatsby-theme-newrelic/src/utils/page-tracking/tessen.js
Confirmed with Rafael in #external-amplitude-team that we need to add an amplitude setting when using latest tessen version.
=> Add amplitude setting when loading tessen

packages/gatsby-theme-newrelic/src/components/SearchModal/SearchModal.js
Update the `type` filter to use what we're setting on the developer site.
=> fix: update swiftype filter for quickstarts

packages/gatsby-theme-newrelic/src/utils/page-tracking/tessen.js
* instead of only grabbing only the pathname, referrer is now set with
the whole url string.
Relates to: #489
=> chore: update referrer to use full url (#489)

packages/gatsby-theme-newrelic/src/components/Link.js
This removes the logic which adds a locale to external links to `newrelic.com`. we can't guarantee these paths exist at the moment
=> Remove external link localization

packages/gatsby-theme-newrelic/src/components/Link.js
* we forgot to modify handleExternalLinkClick the same way we modified
handleInternalLinkClick by passing the onClick parameter. Updated so
they are now in parity.
Relates to: https://github.com/newrelic/developer-website/issues/1850
=> chore: update handleExternalLinkClick to pass onClick parameter

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
- Add a longer debounce time to match search on IO page
- Add conditional to only send analytics via `pageAction` if search query string is 3 or greater
=> [Analytics] Improve debounced search term reporting to avoid tracking incomplete searches

packages/gatsby-theme-newrelic/src/utils/page-tracking/tessen.js
Adds a property to `tessen.page()` calls to tell Segment (and therefore Google Analytics) that it's not an interaction event so Google can accurately calculate bounce rate.
This surfaced only recently because we are now only using Tessen events to send to GA so it became more obvious
Worth noting there's a corresponding `track()` call that is also fired when a `page()` is fired. Verified locally that this prop is on both.
- Closes https://github.com/newrelic/docs-website/issues/4583
- Jira ONYX-1312
- https://segment.com/docs/connections/destinations/catalog/google-analytics/#non-interaction-events
=> [Tessen] Add property to page calls to fix google analytics bounce rate issue

packages/gatsby-theme-newrelic/src/hooks/__tests__/useInstrumentedHandler.js, packages/gatsby-theme-newrelic/src/utils/createTessen.js
If available reads the `ajs_anonymous_id` cookie set by segment and adds that value as the `anonymousId` property in all tessen calls.
This value is stored with encoded quotes (`%22`), so we use `JSON.parse()` to parse it (similar to the PLG code the ticket linked to. Also did that to `ajs_user_id` just in case (even though that value seems to stored without encoding.
Closes https://github.com/newrelic/gatsby-theme-newrelic/issues/563
=> feat(tessen): add segment anonymous id to tessen calls

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/RelatedResources.js
We were already tracking the URL the user was sent to. 
- `relatedResourcesLinkClick` property: `href`
I added the referrer URL that the user came from. 
- `relatedResourcesLinkClick` property: ~~`referrer`~~ `currentUrl`
closes: https://github.com/newrelic/gatsby-theme-newrelic/issues/538
=> chore: add referrer url to RelatedResources clicks

demo/gatsby-config.js, packages/gatsby-theme-newrelic/src/utils/page-tracking/tessen.js
BREAKING CHANGE: with the function signature changes we made to tessen, code changes will be required in order to use (tessen in) subsequent versions of the theme.
=> fix!: issues with Tessen page

packages/gatsby-theme-newrelic/src/utils/page-tracking/tessen.js
warning was firing because we swapped field names. fixed that up.
=> chore: fixup warning

packages/gatsby-theme-newrelic/src/components/ContributingGuidelines.js
This uses the [useLocale](https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#uselocale) hook to get what locale the current page is, and only display the `Edit Page` button if the locale is `en` (English)
=> chore: only display edit button for english pages

packages/gatsby-theme-newrelic/src/components/SplitTextButton.js
The current `SplitTextButton` does not include an event for clicking on the default, "free account", state. This adds an event so we can properly track clicks.
=> add split event for default state

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
fixed margin for mobile display (specifically when width is at `375px`)
Co-authored-by: LizBaker <lbaker@newrelic.com>
=> fix: adjust header buttons in mobile

packages/gatsby-theme-newrelic/src/components/DarkModeToggle.js, packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/GlobalNavLink.js
1. Global Header navLinks already have `href` but i've added the `component: 'globalHeader'` attribute to be able to identify them more easily
2. New event created:
- `eventName: 'localeDropDownClick',
category: 'LocaleDropDown',
origin: 'gatsbyTheme',
locale,`
3. New Event:
- `eventName: 'darkModeToggleClick',
category: 'DarkModeToggle',
origin: 'gatsbyTheme',
mode: darkModeValue,`
4. Added instrumentation `component: 'headerLogInButton'` to Login Button
=> chore: tessen instrumentation for global header

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/src/components/Link.js
Adds an option to the `Link` component to disable auto localizing the link's path if on localized version of site. This supports machine translation disclaimer work where we need to add the link to the english version of a page in the disclaimer text at the top of localized pages.
Unblocks https://github.com/newrelic/docs-website/issues/2537
=> Add option to disable auto localization of internal links

packages/gatsby-theme-newrelic/src/components/SearchModal/SearchModal.js
I just removed the set heightsbeing applied to the animated Divs when on Mobile, this was preventing the ability to click outside of the SearchModal component to close it because it took up the entire screen
=> fix: can't exit search modal on mobile

package.json
lerna is apparently a ilttle finicky when using an automation token. adding this flag seemed to work for some users.
some info here
https://github.com/lerna/lerna/issues/2788
=> fix(lerna): add flag to bypass unnecessary permissions check

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json, packages/gatsby-theme-newrelic/src/i18n/translations/jp.json
makes the year in the global footer dynamic so we don't have to update it 🎉 
addresses https://github.com/newrelic/gatsby-theme-newrelic/issues/625
=> Make year dynamic in global footer

packages/gatsby-theme-newrelic/gatsby-node.js
Adding a second locale resulted in an endless loop in the onCreatePage function, this adds a check to stop that loop
=> fix: Check if an existing page has a locale other than en

packages/gatsby-theme-newrelic/gatsby/on-pre-render-html.js, packages/gatsby-theme-newrelic/src/utils/page-tracking/tessen.js
Two fixes were made:
* if tessen is unable to be downloaded, we dont want pages to break in the site. Added a check before each instance of usage to ensure tessen exists.
* when using path prefixes, assets are stored underneath the prefix. Currently, the code that adds tessen is looking in a static place. Updated this so that tessen script path incorporates path prefix into src script path.
Relates to: https://github.com/newrelic/instant-observability-website/issues/99
=> fix for tessen not loading

packages/gatsby-theme-newrelic/src/components/Navigation.js
Since `searchTerm` is not a required prop of `Navigation`, we need to anticipate when it might be undefined
=> Search term undefined doesn't destroy navigation

packages/gatsby-theme-newrelic/src/components/Table.js
I added a swiftype index property to the table component in the docs site but realized we don't pass all props so it isn't getting through, this updates the component to pass all props
=> Pass all props to table component

packages/gatsby-theme-newrelic/src/components/GlobalStyles/typography.js
We have the 200-300 weighted versions of the Söhne font, this adds them as part of the font family.
=> Add 200-300 weighted fonts

packages/gatsby-theme-newrelic/src/components/Walkthrough/WalkthroughStep.js
This is to be able to detect whether the step should be active
=> Pass along `onMouseOver` and `onFocus` props to `WalkthroughStep`

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js
Experiment to switch `Start now` signup modal back to link to newrelic.com/signup page to see what affect that has on numbers
=> feat(signup): replace signup modal with link to storefront signup

packages/gatsby-theme-newrelic/src/components/NavLink.js
This way we can pass a name prop which will be used by react-scroll to scroll to the current page in the nav
=> Pass all props to navlink

demo/src/content/build-apps/this-is-a-404.mdx, demo/src/data/sidenav.json, packages/gatsby-theme-newrelic/gatsby-node.js, packages/gatsby-theme-newrelic/gatsby/page-transforms.js
This creates a better way to determine if a page is actually a 404 so the current regex doesn't match on the wrong pages (ex: release notes page urls). By removing the regex and checking the page component name instead, we get a much more solid conditional to render the correct layouts.
You can see this working in the theme demo:
1.  Navigate to `Build apps` > `Publish and deploy your app 404` - the path contains 404, but we are still render the correct layout with the left nav
2. Now navigate to any url that doesn't exist, and the nav should disappear and you will see the correct 404 page.
=> More comprehensive 404 layout conditionals

packages/gatsby-theme-newrelic/src/components/Link.js
In the iframe for embeds, we want to make sure that all relative links for the site turn into external links (to keep parity with the current experience for the nr1 help xp). This change needed to be made in the gatsby theme because the link component we created actually replaces any links that contain the siteUrl with the relative path. 
Once this is released, I can update this PR https://github.com/newrelic/docs-website/pull/9639 to ensure that all links have the `isEmbedPageLink` prop to be true on all MDX content rendered on an embed page.
=> Add prop `isEmbedPageLink` to add `siteUrl` to all relative paths

package.json, yarn.lock
Updating Lerna to v5 does not seem to add any breaking changes to our repo. 
I did attempt a dry run by trying some suggestions from this [github issue thread](https://github.com/lerna/lerna/issues/51) by running `npx lerna publish patch --no-git-tag-version --no-push --dist-tag beta` and as far as I can tell it is working as expected. Here is the local output of that command:
=> Upgrade Lerna to v5

packages/gatsby-theme-newrelic/src/utils/createTessen.js
Previously, we were using `JSON.parse` after reading the cookie value for `ajs_user_id` and `ajs_anonymous_id`. Since those values are strings already, this was throwing an error:
```
Uncaught SyntaxError: Unexpected non-whitespace character after JSON at position [...]
```
* NR-54405
=> Properly setting Tessen values from Cookies

demo/gatsby-config.js, packages/gatsby-theme-newrelic/gatsby/type-defs.js
We were running into an error where the I/O site was looking for `feedback` in both the gatsby config and gql schema but not finding it in either, this alleviates that situation.
=> fix: add feedback data to the gql schema

packages/gatsby-theme-newrelic/src/components/ComplexFeedback.js
The translated stings for the JP pages were longer than the english ones we designed with. The buttons now will wrap in the UI instead of stretching the form. 
Before
After
=> fix: feedback form UI handles long translation strings

packages/gatsby-theme-newrelic/src/components/ComplexFeedback.js
Before we only sent the pathname of the doc page. This sends the full url which will be formatted in Jira as a clickable link by default.
=> Update feedback form to send full url to Jira

packages/gatsby-theme-newrelic/src/components/CodeBlock.js, packages/gatsby-theme-newrelic/src/components/InteractiveForm.js, packages/gatsby-theme-newrelic/src/components/InteractiveOutput.js
This will allow content creators to choose the agent config file name/type that is displayed and downloaded via the modified codeblock
=> Make fileName in CodeBlock dynamic

demo/package.json, packages/gatsby-theme-newrelic/package.json, yarn.lock
the most recent push has updated the demo site sharp plugins to match the ones in the theme package, and now we have
-  one `gatsby-transformer-sharp` 
- one `gatsby-plugin-sharp`
-  two `sharp` but they are both `0.30.x` instead of also including a `0.29.x` version
- ~~the best i can guess the reason for this might be is because we have two gatsby versions. the theme package is at `4.8.2` and the demo is at `4.4.0`~~  - i tried bumping the gatsby version and this did not resolve it. 
so hopefully this helps!
=> Dedupe gatsby transformer sharp

packages/gatsby-theme-newrelic/src/pages/404.js
the filter only ever returned `false` or `undefined`, so all parts of the URL path were getting filtered out and not being used as the query string
when testing this in dev, clicking on the search input caused the browser to navigate to `?q=apache/`, causing the trailing slash to display in the input as well. it looks like this is happening in [gatsby-link](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/src/rewrite-link-path.js#L47). in the minified code from the npm package, the check on [this line](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/src/rewrite-link-path.js#L11) is being minified to just `true`, so the trailing slash is added. i don't see this behavior in production, so i think this is a separate issue
=> fix: auto-fill search query from URL

packages/gatsby-theme-newrelic/gatsby/on-client-entry.js
darkMode is being set to undefined in localStorage somehow. we're still unsure about the why but this at least protects against that and may help the broken js issues
=> Set darkMode in localStorage on client entry

demo/gatsby-config.js, package.json, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/gatsby/on-client-entry.js, packages/gatsby-theme-newrelic/src/components/LoggedInContext.js, packages/gatsby-theme-newrelic/src/hooks/__tests__/useInstrumentedHandler.js, packages/gatsby-theme-newrelic/src/hooks/useInstrumentedHandler.js, packages/gatsby-theme-newrelic/src/hooks/useLoggedIn.js, packages/gatsby-theme-newrelic/src/utils/createTessen.js, yarn.lock
this PR takes the logic @clarkmcadoo and i wrote for [InstallButton.js](https://github.com/newrelic/instant-observability-website/blob/main/src/components/InstallButton.js) and packages it up in the `useLoggedIn` hook and `LoggedInProvider` for easy reuse
check [instant-observability-website#351](https://github.com/newrelic/instant-observability-website/pull/351) for an example usage
=> create `useLoggedIn` hook and `LoggedInProvider`

packages/gatsby-theme-newrelic/src/hooks/useLoggedIn.js
i forgor this didn't have a default export and so i reexported nothing in gatsby-theme-newrelic/index.js
=> fix: add default export for `useLoggedIn`

packages/gatsby-theme-newrelic/src/components/NavItem.js, packages/gatsby-theme-newrelic/src/components/Tabs/BarItem.js
=> fix: small padding tweak to give content in NavItem space

packages/gatsby-theme-newrelic/src/components/SEO.js
if on a page that is the default language (english in our case), change alt link `hreflang` to `x-default`. this _might_ address issue reported recently where some pages at localized URLs with English content surface for en-us based searches.
BEFORE
AFTER
https://issues.newrelic.com/browse/NR-83012
=> fix(SEO): change hreflang on alt link if default language

packages/gatsby-theme-newrelic/src/components/GlobalHeader.js, packages/gatsby-theme-newrelic/src/components/Tabs/BarItem.js
We don't actively use sign up modal, so remove from global header
Other 🧹 up of linting errors
=> fix(header): remove unused SignupModal from global header

demo/src/pages/index.js, packages/gatsby-theme-newrelic/README.md, packages/gatsby-theme-newrelic/index.js, packages/gatsby-theme-newrelic/src/components/Button.js, packages/gatsby-theme-newrelic/src/components/LicenseKey.js, packages/gatsby-theme-newrelic/src/components/__tests__/__snapshots__/Icon.test.js.snap, packages/gatsby-theme-newrelic/src/i18n/translations/en.json, packages/gatsby-theme-newrelic/src/icons/feather.js
- you can tab to the "account license key" text and hit enter to open the popover, but can't tab to the buttons inside it
- clicking the "account license key" text after hovering over it causes the animation to play again. this isn't as important but still looks silly
=> create license key component

demo/package.json, packages/gatsby-theme-newrelic/src/components/DarkModeToggle.js, packages/gatsby-theme-newrelic/src/hooks/useDarkMode/LICENSE, packages/gatsby-theme-newrelic/src/hooks/useDarkMode/createGlobalState.js, packages/gatsby-theme-newrelic/src/hooks/useDarkMode/createPersistedState.js, packages/gatsby-theme-newrelic/src/hooks/useDarkMode/createStorage.js, packages/gatsby-theme-newrelic/src/hooks/useDarkMode/index.js, packages/gatsby-theme-newrelic/src/hooks/useDarkMode/initializeUseDarkMode.js, packages/gatsby-theme-newrelic/src/hooks/useDarkMode/useEventListener.js, packages/gatsby-theme-newrelic/src/hooks/useDarkMode/usePersistedState.js, yarn.lock
When we upgraded to gatsby v4.25.2 something about the [useDarkMode](https://github.com/donavon/use-dark-mode) hook started causing the darkMode value in localStorage to be set to undefined. It's still not completely clear to me why this happened but in copying the code to our repo to dig in further I found it working as-is. Maybe a conflicting package version? Regardless, the package appears to no longer be maintained so it may be best for us to copy the code to a place we can edit it if needed. I included the original license in the folder with the copied content
=> port over useDarkMode hook

packages/gatsby-theme-newrelic/src/components/LicenseKey.js
after changing the font size in `63c1cbef`, the `::after` was too short. moving your mouse too slowly between the button and the popover meant it would hide while you were trying to look at it. this fixes that, and adds a short delay before hiding to give the user the chance to mouse back over it
=> fix: popover closing too early

packages/gatsby-theme-newrelic/src/components/Collapser.js
this allows the `LicenseKey` component to be used within `Collapser`s. previously, the `LicenseKey` popover would be cut off, because it couldn't overflow the container
it doesn't look quite as good, but it does allow the license key popover to display normally
=> fix: use `visibility` instead of `overflow`

packages/gatsby-theme-newrelic/src/components/OneTrust.js
i'm pretty sure this script tag was copy-pasted.
this change makes ESLint stop complaining about it
=> fix: add `eslint-disable` comment to attribute

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/Collapser.js
`visibility: hidden` won't cause children elements to be hidden if they have `visibility: visible`, as is the case when a collapser is inside of another collapser.
this change uses `display: none` instead which will hide all children
=> fix: use `display` instead of `visibility`

packages/gatsby-theme-newrelic/src/components/Collapser.js
this change switches the collapsers from using `display` back to using `visibility` like in `05fe6da5`, but critically, also hides collapsers that are descendants of a collapser that is closed
the change that switched from `visibility` to `display`, `0ce3a48f`, caused an issue with codeblocks inside collapsers. i'm not 100% sure on why, but according to Clark it's because that component does height calculations that fail with `display: none`
it might be useful to compare this change to the first time i tried using `visibility`. you can run this command:
```
git diff 05fe6da5..811a48a -- packages/gatsby-theme-newrelic/src/components/Collapser.js
```
to see that diff
=> fix: fix wrong codeblock height in collapsers

packages/gatsby-theme-newrelic/src/components/Collapser.js
switched back to using `overflow: hidden`, but only when the Collapser is closed.
this lets the Collapser work normally with Codeblocks and not take up extra space, but lets the LicenseKey popover display correctly and not get cut off
=> fix: make collapsers not take up height when closed

demo/gatsby-config.js, packages/gatsby-theme-newrelic/src/components/SearchModal/useSearchQuery.js
We were having an issue where the 404 page would update the query params based on the slug that lead the user to get a page that doesn't exist. Gatsby was adding a trailing slash to this param.  I've added a function that, if there is a trailing slash in the search term, it will be removed.  Also, updated the gatsby-config to match the functionality of the docs site, this enabled me to replicate the bug locally.
to test, visit `/apache` and click into the search bar
=> Add function to ensure no trail slash in q param

packages/gatsby-theme-newrelic/src/components/SignupModal/signup.js
The ajs_anonymous_id is failing to parse as JSON as it is now being set as a cookie as simply a string.  This was causing the signup request to hang and not make a network request to our internal service for signups.
=> ajs_anonymous_id failing to parse because string

demo/gatsby-config.js, packages/gatsby-theme-newrelic/gatsby-config.js
Adds option to `gatsby-plugin-sitemap` config to always exclude `/embed` pages from sitemaps for good measure. On docs site these pages already have a meta `robots` tag set to `noindex`.
Example:
https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/introduction-new-relic-platform/embed/
=> fix(sitemap): exclude embed pages from sitemap always

packages/gatsby-theme-newrelic/src/components/Collapser.js
This makes the animation of the collapser more smooth since the InlinePopover component works differently now.
=> fix: make collapser animation how it used to be

packages/gatsby-theme-newrelic/src/components/SearchModal/ScrollContainer.js, packages/gatsby-theme-newrelic/src/components/SearchModal/SearchModal.js, packages/gatsby-theme-newrelic/src/components/SearchModal/useSearch.js
This PR will make the search modal contain only 7 results and will not fetch more when a user hovers in the Scroll Container
=> fix: make search return 7 results and not fetch any more

packages/gatsby-theme-newrelic/src/components/ComplexFeedback.js, packages/gatsby-theme-newrelic/src/i18n/translations/en.json
The pagetools width is defined in the docs site but these screenshots are examples with a smaller width:
=> Update feedback styles

packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js, packages/gatsby-theme-newrelic/src/components/Popover/Popover.js
the `useCallback` didn't have `show` as a dependency, so it wasn't recalculating the offset correctly. this fixes that and adds `overflow-x: hidden` to the body so that overflowing Popovers don't increase the document size
=> fix Popover offset not working

packages/gatsby-theme-newrelic/src/components/Tabs/Bar.js, packages/gatsby-theme-newrelic/src/components/Tabs/BarItem.js, packages/gatsby-theme-newrelic/src/components/Tabs/Page.js, packages/gatsby-theme-newrelic/src/components/Tabs/Pages.js, packages/gatsby-theme-newrelic/src/components/Tabs/Tabs.js
- check out this branch in the theme repo
- in the docs repo:
- run `cp -r <theme-repo-dir>/packages/gatsby-theme-newrelic/src/components/Tabs/ node_modules/@newrelic/gatsby-theme-newrelic/src/components/Tabs/`
- `yarn clean`
- `BUILD_FOLDERS=synthetics yarn start`
- go to http://localhost:8000/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/
=> fix: add `height: 100%` to fix overflow

packages/gatsby-theme-newrelic/gatsby-node.js
We have a couple PHP docs using apache syntax, which works on github, so I know it's a valid language identifier
Here's an example:
- https://github.com/newrelic/docs-website/blob/develop/src/content/docs/apm/agents/php-agent/configuration/php-directory-ini-settings.mdx
related PR adding apache code blocks:
- https://github.com/newrelic/docs-website/pull/12932
=> Add apache to languages

packages/gatsby-theme-newrelic/index.js
exporting this hook to use in Opensource in place of the npm package in an attempt to resolve darkMode being set to undefined
=> Export useDarkMode hook

packages/gatsby-theme-newrelic/package.json
on the opensource site, this reduces the build output by about a third (3.27MB before vs 1.91MB after)
=> add `sideEffects: false` for tree-shaking

packages/gatsby-theme-newrelic/src/components/CodeBlock.js
By wrapping all code blocks in the live provider we end up with evaluated code which causes console errors, this moves it to only where needed. I was going to refactor the codeblock further but in the interest of time backed away from that as i think it needs more attention
=> Only use live provider around live code

packages/gatsby-theme-newrelic/src/components/TutorialSteps/TutorialStep.js
Sets h2 and h3 to have the same styling within Steps
- visually, the h3s look better in mdx pages within Steps, but h2s show in the PageTools.
- this gives writers the option to add these headers to the TOC without sacrificing styling or requiring a refactor in our components
- we don't seem to be setting our own header font sizes anywhere. the inherited user agent style for h3s is 1.17em
=> Step headers styles

packages/gatsby-theme-newrelic/gatsby-node.js
there aren't any `MarkdownRemark` nodes in the demo, but there are in the docs-website, so we didn't see this before
=> fix: use `fileAbsolutePath` for `MarkdownRemark` nodes

packages/gatsby-theme-newrelic/package.json, yarn.lock
Updates `gatsby-plugin-newrelic` to use a version that will install the latest NR browser agent
=> feat: update gatsby plugin newrelic

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js, packages/gatsby-theme-newrelic/src/icons/PrivacySwitch.js
i added a conditional max-width, because otherwise the last item in the list of links is on a line by itself and it looks weird at larger font sizes/smaller screen sizes
the theme demo doesn't have Osano, so the link we're adding the icon to doesn't show up normally. in GlobalFooter.js, change the `hasOsano` function to always return `true`. then the "Your Privacy Choices" link and the new icon will show up
the behavior of the icon (invert on hover) should match the behavior on newrelic.com. clicking the link will throw an error since Osano isn't defined
=> feat: add privacy icon

packages/gatsby-theme-newrelic/src/components/Collapser.js
This adds copy functionality to the collapser headers and adds an animation when copied
=> Add copy to collapser header

packages/gatsby-theme-newrelic/src/components/CodeBlock.js
Adds some of the code block content to the tessen event to help identify which codeblock is being copied
=> Add codeblock contents to tessen tracking

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/Tabs/Bar.js, packages/gatsby-theme-newrelic/src/components/Tabs/BarItem.js, packages/gatsby-theme-newrelic/src/components/Tabs/Page.js, packages/gatsby-theme-newrelic/src/components/Tabs/Pages.js, packages/gatsby-theme-newrelic/src/components/Tabs/Tabs.js
this PR adds transition animations to the Tabs component and improves their styling. it also updates `useTabs` to use the index for the currently selected tab instead of the id to make some of the logic easier
[tabs animations.webm](https://github.com/newrelic/gatsby-theme-newrelic/assets/14365008/83897e9b-0ef7-4db1-b0dc-e3bbb26ac17f)
- go to demo page
- click tabs
- animations should **_NEVER_** criss-cross (the exiting panel goes one way and the entering panel comes in from another)
- to test the reduced motion version, Firefox is easiest because you can change the setting in `about:config`. to test in Chrome, you need to change the OS setting for it
- in Firefox's `about:config` change the `ui.prefersReducedMotion` field to `1` and refresh the page
- for Chrome, open Mac's Settings > …
=> Tabs UX refresh

demo/src/pages/index.js, packages/gatsby-theme-newrelic/src/components/Tabs/Bar.js, packages/gatsby-theme-newrelic/src/components/Tabs/BarItem.js, packages/gatsby-theme-newrelic/src/components/Tabs/Tabs.js
when selecting a tab, the URL will update with the tab id. going to a URL with a hash will automatically select that tab
- go to theme demo
- try clicking different tabs
- ensure the URL updates with the tab id
- reload the page or copy-paste the URL to a different tab
- make sure the page switches to that tab on load
=> feat: save selected tab in URL hash

demo/src/content/build-apps/build-hello-world-app.mdx, packages/gatsby-theme-newrelic/src/components/Collapser.js
The collapser header button was only copying the site url and the header hash (not the pathname), this adds the pathname when building the url to be copied
You can test this in the demo by going to the mdx page at `/build-apps/build-hello-world-app/` and clicking the collapser anchor link in the beginning of the doc
=> Fix copied link for collapser headers

packages/gatsby-theme-newrelic/src/components/Tabs/Tabs.js
the `useEffect` in Tabs.js was only running on page load, so linking to a tab on the same page wouldn't update the Tabs. rerunning the effect when `location.hash` changes fixes this
=> fix: update Tabs when clicking link on same page

packages/gatsby-theme-newrelic/src/components/CodeBlock.js, packages/gatsby-theme-newrelic/src/components/InteractiveForm.js, packages/gatsby-theme-newrelic/src/components/Tabs/Tabs.js
this check worked fine on the index page in the demo site. but MDX pages have slightly different element types, so this check was failing, causing the linking to not work at all.
the check isn't really necessary, i was just trying to be extra safe and it ended up breaking things 🙃
=> fix: tabs not linking on MDX pages

README.md, packages/gatsby-theme-newrelic/src/components/SearchModal/NoResults.js
Swapping `explorer's hub` to `support forum`
=> Change explorers hub name

packages/gatsby-theme-newrelic/src/components/Walkthrough/Walkthrough.js
This adds a bit of padding to the walkthrough container to avoid the step numbers spilling out. Here are some screenshots of this change in a tab and standalone in a doc:
=> Add padding to walkthrough container

packages/gatsby-theme-newrelic/src/utils/page-tracking/segment.js
the anonymous id is only sometimes being set in the current form. switching to this format to see if we can get it showing up more reliably
=> Use cookie instead of segment for anon id

packages/gatsby-theme-newrelic/gatsby/on-route-update.js
Add `customer_user_is` and `loggedIn` attributes to NR Browser Agent events
You can see the data being reported [here](https://staging.onenr.io/0gbRKxreOjE).
(_`loggedIn` NRQL query will always return `false` outside of `*.newrelic.com` or `localhost`_)
=> fix: add custom attributes to browser agent events

demo/gatsby-config.js, demo/package.json, packages/gatsby-theme-newrelic/package.json
- update config format for `gatsby-plugin-newrelic`
- remove deprecated use of `GATSBY_NEWRELIC_ENV` build variable to determine multiple environments
=> fix: update gatsby-plugin-newrelic config

demo/src/content/build-apps/this-is-a-404.mdx, packages/gatsby-theme-newrelic/src/components/Link.js, packages/gatsby-theme-newrelic/src/components/MDX.js
Adds an exclusion to our `isExternal()` conditional to prevent our i18n Netlify sites rendering with an external link icon.
https://deploy-preview-1012--newrelic-gatbsy-theme-demo.netlify.app/build-apps/this-is-a-404/
before
after
=> fix: add exclusion to external sites icon for i18n preview sites

packages/gatsby-theme-newrelic/src/components/Lightbox.js
removes horizontal scroll from lightbox
Also fixes bug where width set in mdx tags in docs-website carries over to lightbox and creates unnecessary whitespace
before:
after:
made the window teeny tiny and the image shrinks horizontally with the page, but turns on the scroll bar for vertical shrinking
=> fix: remove scroll from lightbox

packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js, packages/gatsby-theme-newrelic/src/components/Lightbox.js
adjusts the spacing of list items and images and adjusts the line heights of paragraph, h1, and h2 text
the spacing around the main content is changed in [newrelic/docs-website#16583](https://github.com/newrelic/docs-website/pull/16583)
=> feat: adjust line-height and margins for shape up

packages/gatsby-theme-newrelic/src/components/Tabs/Bar.js, packages/gatsby-theme-newrelic/src/components/Tabs/BarItem.js, packages/gatsby-theme-newrelic/src/components/Tabs/Page.js, packages/gatsby-theme-newrelic/src/components/Tabs/Pages.js
this aligns our tab style with the product
docs: <img width="685" alt="Screenshot 2024-03-18 at 2 19 35 PM" src="https://github.com/newrelic/gatsby-theme-newrelic/assets/39655074/1c4d7455-2036-4020-9f30-f705dd58d8ee">
product: <img width="616" alt="Screenshot 2024-03-18 at 2 19 50 PM" src="https://github.com/newrelic/gatsby-theme-newrelic/assets/39655074/b4c16fd7-bf3f-444e-985f-9de169236958">
=> Align tab style with product

packages/gatsby-theme-newrelic/src/components/Link.js
=> fix: removing extra slug portion of redirect urls

packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js, packages/gatsby-theme-newrelic/src/components/TableOfContents.js
Some spacing tweaks:
before / after
before / after
=> fix: spacing in table of contents and h2s

packages/gatsby-theme-newrelic/src/components/GlobalStyles/colors.js, yarn.lock
replaces light mode page background color to requested lighter color.
this uses the var `--system-background-app-light` which is also used in some light icons, but shouldn't cause any visibility issues. I didn't see any obvious ones in the demo site. I'll do the same check in the docs website.
it also pulled in the latest browser agent version?
=> fix: update background color value

demo/src/templates/basic.js, packages/gatsby-theme-newrelic/src/components/ComplexFeedback.js, packages/gatsby-theme-newrelic/src/components/TableOfContents.js
Editing `TableOfContents` and `ComplexFeedback` component styes. These are only used in the docs-website. We can override the `Edit this doc` button styles in docs.
theme demo preview: 
https://deploy-preview-1053--newrelic-gatbsy-theme-demo.netlify.app/build-apps/build-hello-world-app/
Preview in local docs build:
=> Refresh PageTools styles

packages/gatsby-theme-newrelic/src/components/Tabs/BarItem.js
=> fix: use push state vs navigation to keep page from scrolling

packages/gatsby-theme-newrelic/src/components/MarkdownContainer.js
- fixes bug that would continue to increment li number on all children even in a separate ol's
before:
```
1. li
2. li
3. li
4. li
5. li
6. li
7. li
```
after:
```
1. li
1. li
2. li
1. li
2. li
3. li
3. li
```
=> fix: reset ordered list counter on listitems

demo/gatsby-config.js, packages/gatsby-theme-newrelic/gatsby/on-pre-render-html.js, packages/gatsby-theme-newrelic/src/components/Link.js, packages/gatsby-theme-newrelic/src/i18n/translations/fr.json, packages/gatsby-theme-newrelic/src/utils/config/i18n.js
=> Update locales to include french

packages/gatsby-theme-newrelic/src/components/GlobalSearch.js, packages/gatsby-theme-newrelic/src/components/SEO.js, packages/gatsby-theme-newrelic/src/components/SearchInput.js, packages/gatsby-theme-newrelic/src/pages/404.js
- useScrollFreeze added to GlobalSearch
- update old query params with new syntax
=> Search updates

packages/gatsby-theme-newrelic/src/components/GlobalFooter.js, packages/gatsby-theme-newrelic/src/components/GlobalSearch.js
- https://new-relic.atlassian.net/browse/NR-367012 
Clicking on search button makes docs page unscrollable, this has happened because we are using a hook called 
useScrollFreeze , which adds the style of overflow: hidden to the global parent div of the page, this hook is being 
triggered when the search box is focused instead it should get triggered when the searchdropdown is open, made the 
fixes for desirable behaviour  
- https://new-relic.atlassian.net/browse/NR-367023
The content in footer is getting trimmed increased the width of the content which was getting trimmed and took care of 
responsiveness
=> fix: unscrollable when focus is on search , t&c content
